[genus.aliases]
ace = "Acer"
acer = "Acer"
car = "Carya"
cor = "Cornus"
ile = "Ilex"
ille = "Ilex"
jul = "Juniperus"
jun = "Juniperus"
mer = "Morella"
mor = "Morella"
nys = "Nyssa"
pin = "Pinus"
pine = "Pinus"
pru = "Prunus"
que = "Quercus"
uni = "Unidentifiable"
vac = "Vaccinium"
liq = "Liquidambar"
ilex = "Ilex"
morella = "Morella"
nyssa = "Nyssa"
prunus = "Prunus"
quercus = "Quercus"
vaccinium = "Vaccinium"
liquidambar = "Liquidambar"

[species.aliases]
app = "app."
bic = "bicolor"
cer = "cerifera"
cor = "cerifera"
flo = "florida"
mic = "michauxii"
opa = "opaca"
pen = "pensylvanicum"
phe = "phellos"
ser = "serotina"
sty = "styraciflua"
spp = "spp."
syl = "sylvatica"
syi = "sylvatica"
tae = "taeda"
tom = "tomentosa"
vir = "virginiana"
rub = "rubrum"
cerifera = "cerifera"
florida = "florida"
opaca = "opaca"
virginiana = "virginiana"
sppdot = "spp."

[canonical]
unknown_species_placeholder = "spp."
unknown_genus_placeholder = "Unidentifiable"
