---
title: PLOTNAMEPLACEHOLDER
output: pdf_document
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage[table]{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning=FALSE}
cat("WRITE DATE HERE:")
cat("")
cat("")
cat("")
cat("")
print("Tags Already Used:")
tags_used <- sort(
  unique(
    tree_census[
      which(
        tree_census$plot == substr(
          "PLOTNAMEPLACEHOLDER",
          nchar("PLOTNAMEPLACEHOLDER") - 1,
          nchar("PLOTNAMEPLACEHOLDER")
        )
      ),
      "tree_number"
    ]
  )
)
print(as.character(sort(tags_used)))
```

```{r, echo = FALSE, warning = FALSE}
library(kableExtra)
library(rmarkdown)

this_df <- z[["PLOTNAMEPLACEHOLDER"]]

this_df[is.na(this_df)] <- ""

this_df %>%
  kable("latex", booktabs = TRUE, longtable = TRUE, linesep = "") %>%
  kable_styling(
    latex_options = c("striped", "hold_position", "scale_down", "repeat_header"),
    full_width = F,
    repeat_header_text = "\\textit{(PLOTNAMEPLACEHOLDER...)}",
    repeat_header_continued = "\\textit{(PLOTNAMEPLACEHOLDER Continued on Next Page...)}"
  ) %>%
  row_spec(0, bold = TRUE) %>%
  kable_classic(full_width = F, html_font = "Arial") %>%
  column_spec(1:9, border_left = TRUE)
```
