# Forest Salinity 🌲🧂

Here is the code that I have been using to analyze the tree susceptibility to salt.

The code basically starts with data visualization of soil salinity and porewater salinity for all plots, and then moves into tree sensitivity to those two variables based on the proportion of standing dead stems. At the end, I started playing around with survival curves.

I have been meaning to clean it up before I send it to you, but have been pulled in to other things, so you will see that it is an embarrassing mess and breaks all of your good-housekeeping suggestions (for real, I'm so sorry). The only positive is that it is fairly well annotated.

Even so, if you are able to add the piece of weighting to the logistic regressions on the basis of sample number and add confidence intervals to the curves, like we talked about late last year, it would be a big help. I am planning to present this data again in two weeks and would love to keep improving it, and I'm hoping to start to write it up later this spring.

Thank you so much for your help with this! Please ask away if the code is unclear. All of the data files are also attached.
