name: Release Tree Census Dataset

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release_tree_census:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        Rscript -e 'renv::install()'

    - name: Save Outputs
      run: |
        Rscript exec/data_process/trees/release.R

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        body: Gedan lab tree census as of forestsalinity version ${{ github.ref }}
        files: |
          output/tree_census.csv
          output/tree_census.rds
        token: ${{ secrets.GITHUB_TOKEN }}
